### ISSUE TITLE
Doesn't boot on Nougat bootloader.

### ISSUE THREAD

**Issue by gingernut1978** [GUYVER91/LOS#1]
Thank's for your kernel and really sorry to see you've closed all your xda threads. Got personal builds running from your source, much appreciated.

I understand Nougat bootloader is still not final but any insight into why your kernel won't boot when using it?

Is there anyway to get in contact with you?

Take care

**Comment by gingernut1978** [comment]
I reverted that commit and it dosen't boot with nougat bootloader.

No problem just curious as to why.

Self-built stock lineage kernel with absolutly no changes to code doesn't boot either fyi.

**Comment by GUYVER91** [comment]
its UEFI Secure Bootloader which stop standalone compiled kernel from booting alongside Nougat bootloader.

**Comment by gingernut1978** [comment]
Now I get it.

So no way around this at the moment?

**Comment by GUYVER91** [comment]
i'm not sure , maybe if you don't include dtb file in your Flash Script , it boot up alongside Nougat bootloader.

**Comment by gingernut1978** [comment]
I thought when you unlock the bootloader it disabled these kind of checks but obviously not.

Maybe the kernel needs some kind of signing to boot.

**Comment by gingernut1978** [comment]
Possibly VerifiedBootSigner.zip by Chainfire?

I'll give it a test.

Edit: No luck, doesn't boot : (

**Comment by yukkodesu** [comment]
How soon could you please release a **new** version of Kernel Flash **ZIP**? Thanks for updating such a stable kernel.

**Comment by gingernut1978** [comment]
I don't think he'll be releasing any new builds on XDA, he's closed the thread.

Send me your email and I'll send you a link with the latest build.

**Comment by yukkodesu** [comment]
So I need to compile it myself? All right. My email address @Gingernut1978
