### ISSUE TITLE
Fingerprint sensor problems

### ISSUE THREAD

**Issue by gingernut1978** [GUYVER91/LOS#3]
Latest build from master branch gives fingerprint sensor read problems.

Will try to get more details from log.

**Comment by GUYVER91** [comment]
QFP read problem has nothing to do with kernel!
try using correct QFP blob and MiUi FW
for me FP working fine with latest AEX rom ( which is using QFP blob from  7.7.15 ) alongside 7.6.15 MiUi FW

**Comment by gingernut1978** [comment]
Possibly could be another issue but I believe it is a kernel issue, the only modification was a git pull && build, was working perfect before on previous (before up streaming) compiled code.

I do not do any modifications to your code base and use the exact same config as you ( according to your build.sh).

I will manually test updating fingerprint sensor blobs to 7.7.20 but can't use a Miui firmware before 7.7.6 as it's a set minimum requirement by Lineage, also this didn't give me any problems until now.

BYW the command you use for creating dt.img has a few derps. 

Kernel off_set should be at 4096 not 2048 and no need to force on v2 as dtb's are v3. 

This still doesn't get kernel booting on nougat bootloader FYI but I'm still investigating.

**Comment by GUYVER91** [comment]
upstreaming my source has nothing to do with QFP function on kernel!
check the QBT1000 & captouch driver.

i already knew about minimal MiUi FW requirement on LOS!
i changed the 7.6.15 FW so it doesn't make any sound issue on latest AEX.
* fingerprint HAL minimal firmware requirement is still 7.5.15 *
( i already shared it on TG Group )
here is the link for TG Group :
https://t.me/joinchat/AAAAAEQpDhCeu1PAVxN1aw

* fingerprint HAL minimal firmware requirement is still 7.5.15 *

try to compile kernel source alonside the ROM (NDK).
http://uupload.ir/files/xdng_photo_2017-05-09_17-06-34.jpg
http://uupload.ir/files/olxs_photo_2017-05-09_17-15-24.jpg

UEFI Secure bootloader on N Bootloader is really bothersome on Xiaomi SD82x family

**Comment by gingernut1978** [comment]
Bootloader problem is only when building standalone Kernel outside device tree.

Why would I want to use outdated firmware package when it was working perfect on 7.7.20 before latest commits merge.

It's just a possibility that it is a kernel issue even though the fingerprint driver was not touched as it's the only thing I changed before the problem occurred.

I'll start to revert some commits and I'll try with previous toolchain.

**Comment by gingernut1978** [comment]
Close this if you wish as I have reverted a bunch of commits, optimisations and changed back to previous tool chain without solving the problem.

At least on LOS after up-streaming your Capricorn master branch fingerprint reader no longer works correctly even with older Miui firmware.

Your Nagatobimaru branch does not present this sensor problem and works perfect. 

BTW, congrats on the first EAS custom enabled kernel for Capricorn.

Where did you find LOS EAS kernel code?

**Comment by GUYVER91** [comment]
Fixed it , ofast optimization was causing issue on captouch & QBT1000 drivers.( upstreaming had nothing to do with FP issue. )
also made a test branch for users , who don't want a upstreamed kernel.
