### ISSUE TITLE
Main differences between AOSP branch and MIUI branch?

### ISSUE THREAD

**Issue by huming2207** [GUYVER91/LOS#5]
Hello Guyver91,

Sorry for bothering you with a Mi 6's question...

I'm porting some kernel patches from OnePlus 5 to Xiaomi Mi 6. It has been proved working well on AOSP/LineageOS variants. So, I've posted my works to XDA developer forum to share my work. Later someone request me to port a branch to MIUI as it doesn't work on MIUI ROMs and some AOSP ROMs built with Xiaomi stock MIUI kernel. They replied "it got stuck at the Mi logo when booting".

In the beginning I was thinking that probably something went wrong with the ramdisk. But since my kernel flashable zip uses AnyKernel2 script, it should patches the kernel binary itself only, not the whole boot partition including the ramdisk. So, the ramdisk is not the major issue in this occasion.

So... I would like to ask that is there anything I need to change to make my kernel works on MIUI ROMs? I've tried do `diff` with your AOSP branch but there are quite a lot of irrelevant changes which made me feeling more confused.

Thanks & Regards,
Jackson Hu

**Comment by GUYVER91** [comment]
Hi Mate 
the main difference between MiUi and CAF-AOSP kernel source is wlan module ( MiUi need wlan module ( wlan.ko ) w/o MODULE_SIG.

**Comment by huming2207** [comment]
Hi Guyver91,

Thanks for your reply. Looks like Mi 6's issue is more complex, someone reported that it even didn't boot when using MIUI with my kernel.

By the way, I would also like to ask that is there any debug method (e.g. console output via UART serial port?) to debug the kernel when there is no `adb` access?
